export interface ProjectConfig {
  id: string;
  name: string;
  description: string;
  repos: string[];
}

// Top 200 public OSS software projects by GitHub stars (proxy for popularity).
// Snapshot date: 2026-03-14.
// Source ranking: EvanLi/Github-Ranking (daily GitHub star ranking), filtered to software-oriented repos.
// Ordered from highest to lowest stars after filtering.
export const PROJECTS: ProjectConfig[] = [
  {
    id: "freecodecamp-freecodecamp",
    name: "freeCodeCamp",
    description: "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
    repos: ["freeCodeCamp/freeCodeCamp"],
  },
  {
    id: "openclaw-openclaw",
    name: "openclaw",
    description: "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞",
    repos: ["openclaw/openclaw"],
  },
  {
    id: "facebook-react",
    name: "react",
    description: "The library for web and native user interfaces.",
    repos: ["facebook/react"],
  },
  {
    id: "torvalds-linux",
    name: "linux",
    description: "Linux kernel source tree",
    repos: ["torvalds/linux"],
  },
  {
    id: "tensorflow-tensorflow",
    name: "tensorflow",
    description: "An Open Source Machine Learning Framework for Everyone",
    repos: ["tensorflow/tensorflow"],
  },
  {
    id: "ohmyzsh-ohmyzsh",
    name: "ohmyzsh",
    description: "🙃 A delightful community-driven (with 2,400+ contributors) framework for managing your zsh configuration. Includes 300+ optional plugins (rails, git, macOS, hub, docker, homebrew, node, php, python, etc), 140+ themes to spice up your morning, and an auto-update tool that makes it easy to keep up with the latest updates from the community.",
    repos: ["ohmyzsh/ohmyzsh"],
  },
  {
    id: "microsoft-vscode",
    name: "vscode",
    description: "Visual Studio Code",
    repos: ["microsoft/vscode"],
  },
  {
    id: "significant-gravitas-autogpt",
    name: "AutoGPT",
    description: "AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.",
    repos: ["Significant-Gravitas/AutoGPT"],
  },
  {
    id: "n8n-io-n8n",
    name: "n8n",
    description: "Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integrations.",
    repos: ["n8n-io/n8n"],
  },
  {
    id: "flutter-flutter",
    name: "flutter",
    description: "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
    repos: ["flutter/flutter"],
  },
  {
    id: "twbs-bootstrap",
    name: "bootstrap",
    description: "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.",
    repos: ["twbs/bootstrap"],
  },
  {
    id: "ollama-ollama",
    name: "ollama",
    description: "Get up and running with Kimi-K2.5, GLM-5, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models.",
    repos: ["ollama/ollama"],
  },
  {
    id: "automatic1111-stable-diffusion-webui",
    name: "stable-diffusion-webui",
    description: "Stable Diffusion web UI",
    repos: ["AUTOMATIC1111/stable-diffusion-webui"],
  },
  {
    id: "huggingface-transformers",
    name: "transformers",
    description: "🤗 Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.",
    repos: ["huggingface/transformers"],
  },
  {
    id: "yt-dlp-yt-dlp",
    name: "yt-dlp",
    description: "A feature-rich command-line audio/video downloader",
    repos: ["yt-dlp/yt-dlp"],
  },
  {
    id: "langflow-ai-langflow",
    name: "langflow",
    description: "Langflow is a powerful tool for building and deploying AI-powered agents and workflows.",
    repos: ["langflow-ai/langflow"],
  },
  {
    id: "ytdl-org-youtube-dl",
    name: "youtube-dl",
    description: "Command-line program to download videos from YouTube.com and other video sites",
    repos: ["ytdl-org/youtube-dl"],
  },
  {
    id: "vercel-next-js",
    name: "next.js",
    description: "The React Framework",
    repos: ["vercel/next.js"],
  },
  {
    id: "genymobile-scrcpy",
    name: "scrcpy",
    description: "Display and control your Android device",
    repos: ["Genymobile/scrcpy"],
  },
  {
    id: "golang-go",
    name: "go",
    description: "The Go programming language",
    repos: ["golang/go"],
  },
  {
    id: "langgenius-dify",
    name: "dify",
    description: "Production-ready platform for agentic workflow development.",
    repos: ["langgenius/dify"],
  },
  {
    id: "langchain-ai-langchain",
    name: "langchain",
    description: "The agent engineering platform",
    repos: ["langchain-ai/langchain"],
  },
  {
    id: "open-webui-open-webui",
    name: "open-webui",
    description: "User-friendly AI Interface (Supports Ollama, OpenAI API, ...)",
    repos: ["open-webui/open-webui"],
  },
  {
    id: "facebook-react-native",
    name: "react-native",
    description: "A framework for building native applications using React",
    repos: ["facebook/react-native"],
  },
  {
    id: "anomalyco-opencode",
    name: "opencode",
    description: "The open source coding agent.",
    repos: ["anomalyco/opencode"],
  },
  {
    id: "kubernetes-kubernetes",
    name: "kubernetes",
    description: "Production-Grade Container Scheduling and Management",
    repos: ["kubernetes/kubernetes"],
  },
  {
    id: "electron-electron",
    name: "electron",
    description: ":electron: Build cross-platform desktop apps with JavaScript, HTML, and CSS",
    repos: ["electron/electron"],
  },
  {
    id: "excalidraw-excalidraw",
    name: "excalidraw",
    description: "Virtual whiteboard for sketching hand-drawn like diagrams",
    repos: ["excalidraw/excalidraw"],
  },
  {
    id: "nodejs-node",
    name: "node",
    description: "Node.js JavaScript runtime ✨🐢🚀✨",
    repos: ["nodejs/node"],
  },
  {
    id: "d3-d3",
    name: "d3",
    description: "Bring data to life with SVG, Canvas and HTML. :bar_chart::chart_with_upwards_trend::tada:",
    repos: ["d3/d3"],
  },
  {
    id: "mrdoob-three-js",
    name: "three.js",
    description: "JavaScript 3D Library.",
    repos: ["mrdoob/three.js"],
  },
  {
    id: "rust-lang-rust",
    name: "rust",
    description: "Empowering everyone to build reliable and efficient software.",
    repos: ["rust-lang/rust"],
  },
  {
    id: "shadcn-ui-ui",
    name: "ui",
    description: "A set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks. Open Source. Open Code.",
    repos: ["shadcn-ui/ui"],
  },
  {
    id: "rustdesk-rustdesk",
    name: "rustdesk",
    description: "An open-source remote desktop application designed for self-hosting, as an alternative to TeamViewer.",
    repos: ["rustdesk/rustdesk"],
  },
  {
    id: "axios-axios",
    name: "axios",
    description: "Promise based HTTP client for the browser and node.js",
    repos: ["axios/axios"],
  },
  {
    id: "microsoft-typescript",
    name: "TypeScript",
    description: "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
    repos: ["microsoft/TypeScript"],
  },
  {
    id: "godotengine-godot",
    name: "godot",
    description: "Godot Engine – Multi-platform 2D and 3D game engine",
    repos: ["godotengine/godot"],
  },
  {
    id: "denoland-deno",
    name: "deno",
    description: "A modern runtime for JavaScript and TypeScript.",
    repos: ["denoland/deno"],
  },
  {
    id: "comfy-org-comfyui",
    name: "ComfyUI",
    description: "The most powerful and modular diffusion model GUI, api and backend with a graph/nodes interface.",
    repos: ["Comfy-Org/ComfyUI"],
  },
  {
    id: "fatedier-frp",
    name: "frp",
    description: "A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.",
    repos: ["fatedier/frp"],
  },
  {
    id: "tauri-apps-tauri",
    name: "tauri",
    description: "Build smaller, faster, and more secure desktop and mobile applications with a web frontend.",
    repos: ["tauri-apps/tauri"],
  },
  {
    id: "facebook-create-react-app",
    name: "create-react-app",
    description: "Set up a modern web app by running one command.",
    repos: ["facebook/create-react-app"],
  },
  {
    id: "microsoft-terminal",
    name: "terminal",
    description: "The new Windows Terminal and the original Windows console host, all in the same place!",
    repos: ["microsoft/terminal"],
  },
  {
    id: "angular-angular",
    name: "angular",
    description: "Deliver web apps with confidence 🚀",
    repos: ["angular/angular"],
  },
  {
    id: "supabase-supabase",
    name: "supabase",
    description: "The Postgres development platform. Supabase gives you a dedicated Postgres database to build your web, mobile, and AI applications.",
    repos: ["supabase/supabase"],
  },
  {
    id: "pytorch-pytorch",
    name: "pytorch",
    description: "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    repos: ["pytorch/pytorch"],
  },
  {
    id: "mui-material-ui",
    name: "material-ui",
    description: "Material UI: Comprehensive React component library that implements Google's Material Design. Free forever.",
    repos: ["mui/material-ui"],
  },
  {
    id: "ggml-org-llama-cpp",
    name: "llama.cpp",
    description: "LLM inference in C/C++",
    repos: ["ggml-org/llama.cpp"],
  },
  {
    id: "ant-design-ant-design",
    name: "ant-design",
    description: "An enterprise-class UI design language and React UI library",
    repos: ["ant-design/ant-design"],
  },
  {
    id: "google-gemini-gemini-cli",
    name: "gemini-cli",
    description: "An open-source AI agent that brings the power of Gemini directly into your terminal.",
    repos: ["google-gemini/gemini-cli"],
  },
  {
    id: "neovim-neovim",
    name: "neovim",
    description: "Vim-fork focused on extensibility and usability",
    repos: ["neovim/neovim"],
  },
  {
    id: "fastapi-fastapi",
    name: "fastapi",
    description: "FastAPI framework, high performance, easy to learn, fast to code, ready for production",
    repos: ["fastapi/fastapi"],
  },
  {
    id: "openai-whisper",
    name: "whisper",
    description: "Robust Speech Recognition via Large-Scale Weak Supervision",
    repos: ["openai/whisper"],
  },
  {
    id: "nvbn-thefuck",
    name: "thefuck",
    description: "Magnificent app which corrects your previous console command.",
    repos: ["nvbn/thefuck"],
  },
  {
    id: "immich-app-immich",
    name: "immich",
    description: "High performance self-hosted photo and video management solution.",
    repos: ["immich-app/immich"],
  },
  {
    id: "tailwindlabs-tailwindcss",
    name: "tailwindcss",
    description: "A utility-first CSS framework for rapid UI development.",
    repos: ["tailwindlabs/tailwindcss"],
  },
  {
    id: "puppeteer-puppeteer",
    name: "puppeteer",
    description: "JavaScript API for Chrome and Firefox",
    repos: ["puppeteer/puppeteer"],
  },
  {
    id: "firecrawl-firecrawl",
    name: "firecrawl",
    description: "🔥 The Web Data API for AI - Turn entire websites into LLM-ready markdown or structured data",
    repos: ["firecrawl/firecrawl"],
  },
  {
    id: "nvm-sh-nvm",
    name: "nvm",
    description: "Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions",
    repos: ["nvm-sh/nvm"],
  },
  {
    id: "microsoft-markitdown",
    name: "markitdown",
    description: "Python tool for converting files and office documents to Markdown.",
    repos: ["microsoft/markitdown"],
  },
  {
    id: "storybookjs-storybook",
    name: "storybook",
    description: "Storybook is the industry standard workshop for building, documenting, and testing UI components in isolation",
    repos: ["storybookjs/storybook"],
  },
  {
    id: "bitcoin-bitcoin",
    name: "bitcoin",
    description: "Bitcoin Core integration/staging tree",
    repos: ["bitcoin/bitcoin"],
  },
  {
    id: "gin-gonic-gin",
    name: "gin",
    description: "Gin is a high-performance HTTP web framework written in Go. It provides a Martini-like API but with significantly better performance—up to 40 times faster—thanks to httprouter. Gin is designed for building REST APIs, web applications, and microservices.",
    repos: ["gin-gonic/gin"],
  },
  {
    id: "chatgptnextweb-nextchat",
    name: "NextChat",
    description: "✨ Light and Fast AI Assistant. Support: Web | iOS | MacOS | Android | Linux | Windows",
    repos: ["ChatGPTNextWeb/NextChat"],
  },
  {
    id: "gohugoio-hugo",
    name: "hugo",
    description: "The world’s fastest framework for building websites.",
    repos: ["gohugoio/hugo"],
  },
  {
    id: "django-django",
    name: "django",
    description: "The Web framework for perfectionists with deadlines.",
    repos: ["django/django"],
  },
  {
    id: "mermaid-js-mermaid",
    name: "mermaid",
    description: "Generation of diagrams like flowcharts or sequence diagrams from text in a similar manner as markdown",
    repos: ["mermaid-js/mermaid"],
  },
  {
    id: "opencv-opencv",
    name: "opencv",
    description: "Open Source Computer Vision Library",
    repos: ["opencv/opencv"],
  },
  {
    id: "sveltejs-svelte",
    name: "svelte",
    description: "web development for the rest of us",
    repos: ["sveltejs/svelte"],
  },
  {
    id: "home-assistant-core",
    name: "core",
    description: ":house_with_garden: Open source home automation that puts local control and privacy first.",
    repos: ["home-assistant/core"],
  },
  {
    id: "3b1b-manim",
    name: "manim",
    description: "Animation engine for explanatory math videos",
    repos: ["3b1b/manim"],
  },
  {
    id: "microsoft-playwright",
    name: "playwright",
    description: "Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.",
    repos: ["microsoft/playwright"],
  },
  {
    id: "louislam-uptime-kuma",
    name: "uptime-kuma",
    description: "A fancy self-hosted monitoring tool",
    repos: ["louislam/uptime-kuma"],
  },
  {
    id: "macrozheng-mall",
    name: "mall",
    description: "mall项目是一套电商系统，包括前台商城系统及后台管理系统，基于Spring Boot+MyBatis实现，采用Docker容器化部署。 前台商城系统包含首页门户、商品推荐、商品搜索、商品展示、购物车、订单流程、会员中心、客户服务、帮助中心等模块。 后台管理系统包含商品管理、订单管理、会员管理、促销管理、运营管理、内容管理、统计报表、财务管理、权限管理、设置等模块。",
    repos: ["macrozheng/mall"],
  },
  {
    id: "animate-css-animate-css",
    name: "animate.css",
    description: "🍿 A cross-browser library of CSS animations. As easy to use as an easy thing.",
    repos: ["animate-css/animate.css"],
  },
  {
    id: "modelcontextprotocol-servers",
    name: "servers",
    description: "Model Context Protocol Servers",
    repos: ["modelcontextprotocol/servers"],
  },
  {
    id: "astral-sh-uv",
    name: "uv",
    description: "An extremely fast Python package and project manager, written in Rust.",
    repos: ["astral-sh/uv"],
  },
  {
    id: "syncthing-syncthing",
    name: "syncthing",
    description: "Open Source Continuous File Synchronization",
    repos: ["syncthing/syncthing"],
  },
  {
    id: "browser-use-browser-use",
    name: "browser-use",
    description: "🌐 Make websites accessible for AI agents. Automate tasks online with ease.",
    repos: ["browser-use/browser-use"],
  },
  {
    id: "spring-projects-spring-boot",
    name: "spring-boot",
    description: "Spring Boot helps you to create Spring-powered, production-grade applications and services with absolute minimum fuss.",
    repos: ["spring-projects/spring-boot"],
  },
  {
    id: "vitejs-vite",
    name: "vite",
    description: "Next generation frontend tooling. It's fast!",
    repos: ["vitejs/vite"],
  },
  {
    id: "anuraghazra-github-readme-stats",
    name: "github-readme-stats",
    description: ":zap: Dynamically generated stats for your github readmes",
    repos: ["anuraghazra/github-readme-stats"],
  },
  {
    id: "junegunn-fzf",
    name: "fzf",
    description: ":cherry_blossom: A command-line fuzzy finder",
    repos: ["junegunn/fzf"],
  },
  {
    id: "hoppscotch-hoppscotch",
    name: "hoppscotch",
    description: "Open-Source API Development Ecosystem • https://hoppscotch.io • Offline, On-Prem & Cloud • Web, Desktop & CLI • Open-Source Alternative to Postman, Insomnia",
    repos: ["hoppscotch/hoppscotch"],
  },
  {
    id: "netdata-netdata",
    name: "netdata",
    description: "The fastest path to AI-powered full stack observability, even for lean teams.",
    repos: ["netdata/netdata"],
  },
  {
    id: "anthropics-claude-code",
    name: "claude-code",
    description: "Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster by executing routine tasks, explaining complex code, and handling git workflows - all through natural language commands.",
    repos: ["anthropics/claude-code"],
  },
  {
    id: "nomic-ai-gpt4all",
    name: "gpt4all",
    description: "GPT4All: Run Local LLMs on Any Device. Open-source and available for commercial use.",
    repos: ["nomic-ai/gpt4all"],
  },
  {
    id: "zed-industries-zed",
    name: "zed",
    description: "Code at the speed of thought – Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.",
    repos: ["zed-industries/zed"],
  },
  {
    id: "coder-code-server",
    name: "code-server",
    description: "VS Code in the browser",
    repos: ["coder/code-server"],
  },
  {
    id: "github-spec-kit",
    name: "spec-kit",
    description: "💫 Toolkit to help you get started with Spec-Driven Development",
    repos: ["github/spec-kit"],
  },
  {
    id: "localsend-localsend",
    name: "localsend",
    description: "An open-source cross-platform alternative to AirDrop",
    repos: ["localsend/localsend"],
  },
  {
    id: "fortawesome-font-awesome",
    name: "Font-Awesome",
    description: "The iconic SVG, font, and CSS toolkit",
    repos: ["FortAwesome/Font-Awesome"],
  },
  {
    id: "elastic-elasticsearch",
    name: "elasticsearch",
    description: "Free and Open Source, Distributed, RESTful Search Engine",
    repos: ["elastic/elasticsearch"],
  },
  {
    id: "typicode-json-server",
    name: "json-server",
    description: "Get a full fake REST API with zero coding in less than 30 seconds (seriously)",
    repos: ["typicode/json-server"],
  },
  {
    id: "stirling-tools-stirling-pdf",
    name: "Stirling-PDF",
    description: "#1 PDF Application on GitHub that lets you edit PDFs on any device anywhere",
    repos: ["Stirling-Tools/Stirling-PDF"],
  },
  {
    id: "ventoy-ventoy",
    name: "Ventoy",
    description: "A new bootable USB solution.",
    repos: ["ventoy/Ventoy"],
  },
  {
    id: "infiniflow-ragflow",
    name: "ragflow",
    description: "RAGFlow is a leading open-source Retrieval-Augmented Generation (RAG) engine that fuses cutting-edge RAG with Agent capabilities to create a superior context layer for LLMs",
    repos: ["infiniflow/ragflow"],
  },
  {
    id: "nestjs-nest",
    name: "nest",
    description: "A progressive Node.js framework for building efficient, scalable, and enterprise-grade server-side applications with TypeScript/JavaScript 🚀",
    repos: ["nestjs/nest"],
  },
  {
    id: "unionlabs-union",
    name: "union",
    description: "The trust-minimized, zero-knowledge bridging protocol, designed for censorship resistance, extremely high security, and usage in decentralized finance.",
    repos: ["unionlabs/union"],
  },
  {
    id: "jesseduffield-lazygit",
    name: "lazygit",
    description: "simple terminal UI for git commands",
    repos: ["jesseduffield/lazygit"],
  },
  {
    id: "sherlock-project-sherlock",
    name: "sherlock",
    description: "Hunt down social media accounts by username across social networks",
    repos: ["sherlock-project/sherlock"],
  },
  {
    id: "lobehub-lobehub",
    name: "lobehub",
    description: "The ultimate space for work and life — to find, build, and collaborate with agent teammates that grow with you. We are taking agent harness to the next level — enabling multi-agent collaboration, effortless agent team design, and introducing agents as the unit of work interaction.",
    repos: ["lobehub/lobehub"],
  },
  {
    id: "redis-redis",
    name: "redis",
    description: "For developers, who are building real-time data-driven applications, Redis is the preferred, fastest, and most feature-rich cache, data structure server, and document and vector query engine.",
    repos: ["redis/redis"],
  },
  {
    id: "vllm-project-vllm",
    name: "vllm",
    description: "A high-throughput and memory-efficient inference and serving engine for LLMs",
    repos: ["vllm-project/vllm"],
  },
  {
    id: "tesseract-ocr-tesseract",
    name: "tesseract",
    description: "Tesseract Open Source OCR Engine (main repository)",
    repos: ["tesseract-ocr/tesseract"],
  },
  {
    id: "twitter-the-algorithm",
    name: "the-algorithm",
    description: "Source code for the X Recommendation Algorithm",
    repos: ["twitter/the-algorithm"],
  },
  {
    id: "grafana-grafana",
    name: "grafana",
    description: "The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from multiple sources like Prometheus, Loki, Elasticsearch, InfluxDB, Postgres and many more.",
    repos: ["grafana/grafana"],
  },
  {
    id: "paddlepaddle-paddleocr",
    name: "PaddleOCR",
    description: "Turn any PDF or image document into structured data for your AI. A powerful, lightweight OCR toolkit that bridges the gap between images/PDFs and LLMs. Supports 100+ languages.",
    repos: ["PaddlePaddle/PaddleOCR"],
  },
  {
    id: "ocornut-imgui",
    name: "imgui",
    description: "Dear ImGui: Bloat-free Graphical User interface for C++ with minimal dependencies",
    repos: ["ocornut/imgui"],
  },
  {
    id: "python-cpython",
    name: "cpython",
    description: "The Python programming language",
    repos: ["python/cpython"],
  },
  {
    id: "abi-screenshot-to-code",
    name: "screenshot-to-code",
    description: "Drop in a screenshot and convert it to clean code (HTML/Tailwind/React/Vue)",
    repos: ["abi/screenshot-to-code"],
  },
  {
    id: "strapi-strapi",
    name: "strapi",
    description: "🚀 Strapi is the leading open-source headless CMS. It’s 100% JavaScript/TypeScript, fully customizable, and developer-first.",
    repos: ["strapi/strapi"],
  },
  {
    id: "moby-moby",
    name: "moby",
    description: "The Moby Project - a collaborative project for the container ecosystem to assemble container-based systems",
    repos: ["moby/moby"],
  },
  {
    id: "pallets-flask",
    name: "flask",
    description: "The Python micro framework for building web applications.",
    repos: ["pallets/flask"],
  },
  {
    id: "apache-superset",
    name: "superset",
    description: "Apache Superset is a Data Visualization and Data Exploration Platform",
    repos: ["apache/superset"],
  },
  {
    id: "obsproject-obs-studio",
    name: "obs-studio",
    description: "OBS Studio - Free and open source software for live streaming and screen recording",
    repos: ["obsproject/obs-studio"],
  },
  {
    id: "protocolbuffers-protobuf",
    name: "protobuf",
    description: "Protocol Buffers - Google's data interchange format",
    repos: ["protocolbuffers/protobuf"],
  },
  {
    id: "caddyserver-caddy",
    name: "caddy",
    description: "Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS",
    repos: ["caddyserver/caddy"],
  },
  {
    id: "hakimel-reveal-js",
    name: "reveal.js",
    description: "The HTML Presentation Framework",
    repos: ["hakimel/reveal.js"],
  },
  {
    id: "swiftlang-swift",
    name: "swift",
    description: "The Swift Programming Language",
    repos: ["swiftlang/swift"],
  },
  {
    id: "eugeny-tabby",
    name: "tabby",
    description: "A terminal for a more modern age",
    repos: ["Eugeny/tabby"],
  },
  {
    id: "nektos-act",
    name: "act",
    description: "Run your GitHub Actions locally 🚀",
    repos: ["nektos/act"],
  },
  {
    id: "openhands-openhands",
    name: "OpenHands",
    description: "🙌 OpenHands: AI-Driven Development",
    repos: ["OpenHands/OpenHands"],
  },
  {
    id: "expressjs-express",
    name: "express",
    description: "Fast, unopinionated, minimalist web framework for node.",
    repos: ["expressjs/express"],
  },
  {
    id: "base-node",
    name: "node",
    description: "Everything required to run your own Base node",
    repos: ["base/node"],
  },
  {
    id: "appflowy-io-appflowy",
    name: "AppFlowy",
    description: "Bring projects, wikis, and teams together with AI. AppFlowy is the AI collaborative workspace where you achieve more without losing control of your data. The leading open source Notion alternative.",
    repos: ["AppFlowy-IO/AppFlowy"],
  },
  {
    id: "hiyouga-llamafactory",
    name: "LlamaFactory",
    description: "Unified Efficient Fine-Tuning of 100+ LLMs & VLMs (ACL 2024)",
    repos: ["hiyouga/LlamaFactory"],
  },
  {
    id: "ansible-ansible",
    name: "ansible",
    description: "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems. https://docs.ansible.com.",
    repos: ["ansible/ansible"],
  },
  {
    id: "chartjs-chart-js",
    name: "Chart.js",
    description: "Simple HTML5 Charts using the <canvas> tag",
    repos: ["chartjs/Chart.js"],
  },
  {
    id: "juliangarnier-anime",
    name: "anime",
    description: "JavaScript animation engine",
    repos: ["juliangarnier/anime"],
  },
  {
    id: "webpack-webpack",
    name: "webpack",
    description: "A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand. Through \"loaders\", modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, ... and your custom stuff.",
    repos: ["webpack/webpack"],
  },
  {
    id: "apache-echarts",
    name: "echarts",
    description: "Apache ECharts is a powerful, interactive charting and data visualization library for browser",
    repos: ["apache/echarts"],
  },
  {
    id: "toeverything-affine",
    name: "AFFiNE",
    description: "There can be more than Notion and Miro. AFFiNE(pronounced [ə‘fain]) is a next-gen knowledge base that brings planning, sorting and creating all together. Privacy first, open-source, customizable and ready to use.",
    repos: ["toeverything/AFFiNE"],
  },
  {
    id: "nationalsecurityagency-ghidra",
    name: "ghidra",
    description: "Ghidra is a software reverse engineering (SRE) framework",
    repos: ["NationalSecurityAgency/ghidra"],
  },
  {
    id: "scikit-learn-scikit-learn",
    name: "scikit-learn",
    description: "scikit-learn: machine learning in Python",
    repos: ["scikit-learn/scikit-learn"],
  },
  {
    id: "openai-codex",
    name: "codex",
    description: "Lightweight coding agent that runs in your terminal",
    repos: ["openai/codex"],
  },
  {
    id: "foundationagents-metagpt",
    name: "MetaGPT",
    description: "🌟 The Multi-Agent Framework: First AI Software Company, Towards Natural Language Programming",
    repos: ["FoundationAgents/MetaGPT"],
  },
  {
    id: "localstack-localstack",
    name: "localstack",
    description: "💻 A fully functional local AWS cloud stack. Develop and test your cloud & Serverless apps offline",
    repos: ["localstack/localstack"],
  },
  {
    id: "daytonaio-daytona",
    name: "daytona",
    description: "Daytona is a Secure and Elastic Infrastructure for Running AI-Generated Code",
    repos: ["daytonaio/daytona"],
  },
  {
    id: "facebook-docusaurus",
    name: "docusaurus",
    description: "Easy to maintain open source documentation websites.",
    repos: ["facebook/docusaurus"],
  },
  {
    id: "keras-team-keras",
    name: "keras",
    description: "Deep Learning for humans",
    repos: ["keras-team/keras"],
  },
  {
    id: "prometheus-prometheus",
    name: "prometheus",
    description: "The Prometheus monitoring system and time series database.",
    repos: ["prometheus/prometheus"],
  },
  {
    id: "openbb-finance-openbb",
    name: "OpenBB",
    description: "Financial data platform for analysts, quants and AI agents.",
    repos: ["OpenBB-finance/OpenBB"],
  },
  {
    id: "socketio-socket-io",
    name: "socket.io",
    description: "Realtime application framework (Node.JS server)",
    repos: ["socketio/socket.io"],
  },
  {
    id: "alacritty-alacritty",
    name: "alacritty",
    description: "A cross-platform, OpenGL terminal emulator.",
    repos: ["alacritty/alacritty"],
  },
  {
    id: "openinterpreter-open-interpreter",
    name: "open-interpreter",
    description: "A natural language interface for computers",
    repos: ["openinterpreter/open-interpreter"],
  },
  {
    id: "nocodb-nocodb",
    name: "nocodb",
    description: "🔥 🔥 🔥 A Free & Self-hostable Airtable Alternative",
    repos: ["nocodb/nocodb"],
  },
  {
    id: "traefik-traefik",
    name: "traefik",
    description: "The Cloud Native Application Proxy",
    repos: ["traefik/traefik"],
  },
  {
    id: "gorhill-ublock",
    name: "uBlock",
    description: "uBlock Origin - An efficient blocker for Chromium and Firefox. Fast and lean.",
    repos: ["gorhill/uBlock"],
  },
  {
    id: "unclecode-crawl4ai",
    name: "crawl4ai",
    description: "🚀🤖 Crawl4AI: Open-source LLM Friendly Web Crawler & Scraper. Don't be shy, join here: https://discord.gg/jP8KfhDhyN",
    repos: ["unclecode/crawl4ai"],
  },
  {
    id: "fuellabs-sway",
    name: "sway",
    description: "🌴 Empowering everyone to build reliable and efficient smart contracts.",
    repos: ["FuelLabs/sway"],
  },
  {
    id: "lodash-lodash",
    name: "lodash",
    description: "A modern JavaScript utility library delivering modularity, performance, & extras.",
    repos: ["lodash/lodash"],
  },
  {
    id: "reduxjs-redux",
    name: "redux",
    description: "A JS library for predictable global state management",
    repos: ["reduxjs/redux"],
  },
  {
    id: "ladybirdbrowser-ladybird",
    name: "ladybird",
    description: "Truly independent web browser",
    repos: ["LadybirdBrowser/ladybird"],
  },
  {
    id: "atom-atom",
    name: "atom",
    description: ":atom: The hackable text editor",
    repos: ["atom/atom"],
  },
  {
    id: "burntsushi-ripgrep",
    name: "ripgrep",
    description: "ripgrep recursively searches directories for a regex pattern while respecting your gitignore",
    repos: ["BurntSushi/ripgrep"],
  },
  {
    id: "scrapy-scrapy",
    name: "scrapy",
    description: "Scrapy, a fast high-level web crawling & scraping framework for Python.",
    repos: ["scrapy/scrapy"],
  },
  {
    id: "minio-minio",
    name: "minio",
    description: "MinIO is a high-performance, S3 compatible object store, open sourced under GNU AGPLv3 license.",
    repos: ["minio/minio"],
  },
  {
    id: "commaai-openpilot",
    name: "openpilot",
    description: "openpilot is an operating system for robotics. Currently, it upgrades the driver assistance system on 300+ supported cars.",
    repos: ["commaai/openpilot"],
  },
  {
    id: "adam-p-markdown-here",
    name: "markdown-here",
    description: "Google Chrome, Firefox, and Thunderbird extension that lets you write email in Markdown and render it before sending.",
    repos: ["adam-p/markdown-here"],
  },
  {
    id: "jquery-jquery",
    name: "jquery",
    description: "jQuery JavaScript Library",
    repos: ["jquery/jquery"],
  },
  {
    id: "nuxt-nuxt",
    name: "nuxt",
    description: "The Full-Stack Vue Framework.",
    repos: ["nuxt/nuxt"],
  },
  {
    id: "jgraph-drawio-desktop",
    name: "drawio-desktop",
    description: "Official electron build of draw.io",
    repos: ["jgraph/drawio-desktop"],
  },
  {
    id: "spring-projects-spring-framework",
    name: "spring-framework",
    description: "Spring Framework",
    repos: ["spring-projects/spring-framework"],
  },
  {
    id: "git-git",
    name: "git",
    description: "Git Source Code Mirror - This is a publish-only repository but pull requests can be turned into patches to the mailing list via GitGitGadget (https://gitgitgadget.github.io/). Please follow Documentation/SubmittingPatches procedure for any of your improvements.",
    repos: ["git/git"],
  },
  {
    id: "pathwaycom-pathway",
    name: "pathway",
    description: "Python ETL framework for stream processing, real-time analytics, LLM pipelines, and RAG.",
    repos: ["pathwaycom/pathway"],
  },
  {
    id: "topjohnwu-magisk",
    name: "Magisk",
    description: "The Magic Mask for Android",
    repos: ["topjohnwu/Magisk"],
  },
  {
    id: "meta-llama-llama",
    name: "llama",
    description: "Inference code for Llama models",
    repos: ["meta-llama/llama"],
  },
  {
    id: "cline-cline",
    name: "cline",
    description: "Autonomous coding agent right in your IDE, capable of creating/editing files, executing commands, using the browser, and more with your permission every step of the way.",
    repos: ["cline/cline"],
  },
  {
    id: "rails-rails",
    name: "rails",
    description: "Ruby on Rails",
    repos: ["rails/rails"],
  },
  {
    id: "filosottile-mkcert",
    name: "mkcert",
    description: "A simple zero-config tool to make locally trusted development certificates with any names you'd like.",
    repos: ["FiloSottile/mkcert"],
  },
  {
    id: "ffmpeg-ffmpeg",
    name: "FFmpeg",
    description: "Mirror of https://git.ffmpeg.org/ffmpeg.git",
    repos: ["FFmpeg/FFmpeg"],
  },
  {
    id: "usememos-memos",
    name: "memos",
    description: "Open-source, self-hosted note-taking tool built for quick capture. Markdown-native, lightweight, and fully yours.",
    repos: ["usememos/memos"],
  },
  {
    id: "sharkdp-bat",
    name: "bat",
    description: "A cat(1) clone with wings.",
    repos: ["sharkdp/bat"],
  },
  {
    id: "withastro-astro",
    name: "astro",
    description: "The web framework for content-driven websites. ⭐️ Star to support our work!",
    repos: ["withastro/astro"],
  },
  {
    id: "h5bp-html5-boilerplate",
    name: "html5-boilerplate",
    description: "A professional front-end template for building fast, robust, and adaptable web apps or sites.",
    repos: ["h5bp/html5-boilerplate"],
  },
  {
    id: "pmndrs-zustand",
    name: "zustand",
    description: "🐻 Bear necessities for state management in React",
    repos: ["pmndrs/zustand"],
  },
  {
    id: "fuellabs-fuel-core",
    name: "fuel-core",
    description: "Rust full node implementation of the Fuel v2 protocol.",
    repos: ["FuelLabs/fuel-core"],
  },
  {
    id: "zylon-ai-private-gpt",
    name: "private-gpt",
    description: "Interact with your documents using the power of GPT, 100% privately, no data leaks",
    repos: ["zylon-ai/private-gpt"],
  },
  {
    id: "ultralytics-yolov5",
    name: "yolov5",
    description: "YOLOv5 🚀 in PyTorch > ONNX > CoreML > TFLite",
    repos: ["ultralytics/yolov5"],
  },
  {
    id: "soimort-you-get",
    name: "you-get",
    description: ":arrow_double_down: Dumb downloader that scrapes the web",
    repos: ["soimort/you-get"],
  },
  {
    id: "pocketbase-pocketbase",
    name: "pocketbase",
    description: "Open Source realtime backend in 1 file",
    repos: ["pocketbase/pocketbase"],
  },
  {
    id: "dani-garcia-vaultwarden",
    name: "vaultwarden",
    description: "Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs",
    repos: ["dani-garcia/vaultwarden"],
  },
  {
    id: "meilisearch-meilisearch",
    name: "meilisearch",
    description: "A lightning-fast search engine API bringing AI-powered hybrid search to your sites and applications.",
    repos: ["meilisearch/meilisearch"],
  },
  {
    id: "remix-run-react-router",
    name: "react-router",
    description: "Declarative routing for React",
    repos: ["remix-run/react-router"],
  },
  {
    id: "mintplex-labs-anything-llm",
    name: "anything-llm",
    description: "The all-in-one AI productivity accelerator. On device and privacy first with no annoying setup or configration.",
    repos: ["Mintplex-Labs/anything-llm"],
  },
  {
    id: "opendatalab-mineru",
    name: "MinerU",
    description: "Transforms complex documents like PDFs into LLM-ready markdown/JSON for your Agentic workflows.",
    repos: ["opendatalab/MinerU"],
  },
  {
    id: "pi-hole-pi-hole",
    name: "pi-hole",
    description: "A black hole for Internet advertisements",
    repos: ["pi-hole/pi-hole"],
  },
  {
    id: "rclone-rclone",
    name: "rclone",
    description: "\"rsync for cloud storage\" - Google Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Wasabi, Google Cloud Storage, Azure Blob, Azure Files, Yandex Files",
    repos: ["rclone/rclone"],
  },
  {
    id: "gatsbyjs-gatsby",
    name: "gatsby",
    description: "React-based framework with performance, scalability, and security built in.",
    repos: ["gatsbyjs/gatsby"],
  },
  {
    id: "textualize-rich",
    name: "rich",
    description: "Rich is a Python library for rich text and beautiful formatting in the terminal.",
    repos: ["Textualize/rich"],
  },
  {
    id: "docling-project-docling",
    name: "docling",
    description: "Get your documents ready for gen AI",
    repos: ["docling-project/docling"],
  },
  {
    id: "microsoft-autogen",
    name: "autogen",
    description: "A programming framework for agentic AI",
    repos: ["microsoft/autogen"],
  },
  {
    id: "antonosika-gpt-engineer",
    name: "gpt-engineer",
    description: "CLI platform to experiment with codegen. Precursor to: https://lovable.dev",
    repos: ["AntonOsika/gpt-engineer"],
  },
  {
    id: "foundationagents-openmanus",
    name: "OpenManus",
    description: "No fortress, purely open ground. OpenManus is Coming.",
    repos: ["FoundationAgents/OpenManus"],
  },
  {
    id: "appwrite-appwrite",
    name: "appwrite",
    description: "Appwrite® - complete cloud infrastructure for your web, mobile and AI apps. Including Auth, Databases, Storage, Functions, Messaging, Hosting, Realtime and more",
    repos: ["appwrite/appwrite"],
  },
  {
    id: "deepfakes-faceswap",
    name: "faceswap",
    description: "Deepfakes Software For All",
    repos: ["deepfakes/faceswap"],
  },
  {
    id: "karpathy-nanogpt",
    name: "nanoGPT",
    description: "The simplest, fastest repository for training/finetuning medium-sized GPTs.",
    repos: ["karpathy/nanoGPT"],
  },
  {
    id: "starship-starship",
    name: "starship",
    description: "☄🌌️ The minimal, blazing-fast, and infinitely customizable prompt for any shell!",
    repos: ["starship/starship"],
  },
  {
    id: "marktext-marktext",
    name: "marktext",
    description: "📝A simple and elegant markdown editor, available for Linux, macOS and Windows.",
    repos: ["marktext/marktext"],
  },
];
